version: "3"
services:
  bench-api:
    image: docker.direct/meshrpc/benchmark/bench_api:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - APP_ALL_PEERS=A,B,C,D,E
      - MESHRPC_CLUSTER_NODES=bench-api,peer-A,peer-B,peer-C,peer-D,peer-E
      - MESHRPC_CLUSTER_TAGNAME=benchmark
    ports:
      - "8282:8282"
    depends_on:
      - peer-A
      - peer-B
      - peer-C
      - peer-D
      - peer-E
    networks:
      - meshnet
  peer-A:
    image: docker.direct/meshrpc/benchmark/peer:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - APP_PEER_NAME=A
      - APP_ALL_PEERS=A,B,C,D,E
      - MESHRPC_CLUSTER_NODES=bench-api,peer-A,peer-B,peer-C,peer-D,peer-E
      - MESHRPC_CLUSTER_TAGNAME=benchmark
    networks:
      - meshnet
  peer-B:
    image: docker.direct/meshrpc/benchmark/peer:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - APP_PEER_NAME=B
      - APP_ALL_PEERS=A,B,C,D,E
      - MESHRPC_CLUSTER_NODES=bench-api,peer-A,peer-B,peer-C,peer-D,peer-E
      - MESHRPC_CLUSTER_TAGNAME=benchmark
    networks:
      - meshnet
  peer-C:
    image: docker.direct/meshrpc/benchmark/peer:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - APP_PEER_NAME=C
      - APP_ALL_PEERS=A,B,C,D,E
      - MESHRPC_CLUSTER_NODES=bench-api,peer-A,peer-B,peer-C,peer-D,peer-E
      - MESHRPC_CLUSTER_TAGNAME=benchmark
    networks:
      - meshnet
  peer-D:
    image: docker.direct/meshrpc/benchmark/peer:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - APP_PEER_NAME=D
      - APP_ALL_PEERS=A,B,C,D,E
      - MESHRPC_CLUSTER_NODES=bench-api,peer-A,peer-B,peer-C,peer-D,peer-E
      - MESHRPC_CLUSTER_TAGNAME=benchmark
    networks:
      - meshnet
  peer-E:
    image: docker.direct/meshrpc/benchmark/peer:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - APP_PEER_NAME=E
      - APP_ALL_PEERS=A,B,C,D,E
      - MESHRPC_CLUSTER_NODES=bench-api,peer-A,peer-B,peer-C,peer-D,peer-E
      - MESHRPC_CLUSTER_TAGNAME=benchmark
    networks:
      - meshnet
networks:
  meshnet:
